services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SQL_ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_ADMIN_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
