<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>app.jobzy</groupId>
	<artifactId>jobzy-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>jobzy-parent</name>
	<description>Jobzy - making recruitment easy</description>

	<modules>
		<module>jobzy-api</module>
		<module>jobzy-contracts</module>
	</modules>

	<properties>
		<arch-unit.version>1.5.0</arch-unit.version>
		<java.version>25</java.version>
		<lombok.version>1.18.46</lombok.version>
		<maven.compiler.release>${java.version}</maven.compiler.release>
		<mapstruct.version>1.6.3</mapstruct.version>
		<maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
		<rest-assured.version>5.5.0</rest-assured.version>
		<spotless.version>3.8.0</spotless.version>
		<spring-boot.version>4.1.0</spring-boot.version>
		<swagger-annotations.version>2.2.52</swagger-annotations.version>
		<uuid-generator.version>5.2.0</uuid-generator.version>
	</properties>

	<dependencyManagement>
		<dependencies>
		<!-- SPRING			-->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<version>${spring-boot.version}</version>
			</dependency>

		<!-- OTHER			-->
			<dependency>
				<groupId>com.fasterxml.uuid</groupId>
				<artifactId>java-uuid-generator</artifactId>
				<version>${uuid-generator.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
			</dependency>
			<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${mapstruct.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-annotations-jakarta</artifactId>
				<version>${swagger-annotations.version}</version>
			</dependency>

			<!-- TESTING			-->
			<dependency>
				<groupId>io.rest-assured</groupId>
				<artifactId>rest-assured</artifactId>
				<version>${rest-assured.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>com.tngtech.archunit</groupId>
				<artifactId>archunit-junit5</artifactId>
				<version>${arch-unit.version}</version>
				<scope>test</scope>
			</dependency>


		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<version>${spring-boot.version}</version>
				</plugin>
				<plugin>
					<groupId>com.diffplug.spotless</groupId>
					<artifactId>spotless-maven-plugin</artifactId>
					<version>${spotless.version}</version>
					<configuration>
						<java>
							<googleJavaFormat/>
						</java>
					</configuration>
					<executions>
						<execution>
							<id>auto-format</id>
							<phase>process-sources</phase>
							<goals>
								<goal>apply</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>com.diffplug.spotless</groupId>
				<artifactId>spotless-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
