spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  level:
    root: WARN
    com.jobly_jobs: INFO
