package app.jobzy.api.domain.vacancy.valueobject;

public enum VacancyCategory {
  ADMINISTRATION,
  CONSTRUCTION,
  CUSTOMER_SUPPORT,
  DESIGN_CREATIVE,
  EDUCATION,
  ENGINEERING,
  FACILITY_SERVICES,
  FINANCE,
  HEALTHCARE,
  HOSPITALITY,
  HUMAN_RESOURCES,
  LEGAL,
  LOGISTICS_SUPPLY_CHAIN,
  MANAGEMENT,
  MARKETING,
  OPERATIONS,
  PRODUCTION_MANUFACTURING,
  RETAIL,
  SALES,
  SCIENCE_RESEARCH,
  OTHER
}
