spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=jobzy;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    password: Super_secret-123
    username: sa

logging:
  level:
    app.jobzy: DEBUG
